site_name: ABCI 2.0 User Guide
site_description: ABCI 2.0 User Guide, English version
site_author: AIST
site_url: https://docs.abci.ai/en/
repo_url: https://github.com/aistairc/abci-docs
edit_uri: edit/master/en/docs/
copyright: 'Copyright &copy; 2021 National Institute of Advanced Industrial Science and Technology (AIST)'
google_analytics:
  - 'UA-118371652-2'
  - 'auto'
nav:
  - 'Introduction': 'index.md'
  - 'ABCI System Overview': '01.md'
  - 'ABCI System User Environment': '02.md'
  - 'Job Execution Environment': '03.md'
  - 'Storage': '04.md'
  - 'Environment Modules': '05.md'
  - 'Python': '06.md'
  - 'GPU': '07.md'
  - 'MPI': '08.md'
  - 'Linux Containers': '09.md'
  - 'Development Tools': 'development-tools.md'
  - 'Appendix':
    - 'Appendix. Configuration of Installed Software': 'appendix/installed-software.md'
    - 'Appendix. Using ABCI with HPCI': 'appendix/using-abci-with-hpci.md'
    - 'Appendix. Communications with External Networks': 'appendix/external-networks.md'
    - 'Appendix. SSH Access to Compute Nodes': 'appendix/ssh-access.md'
  - 'Applications':
    - 'Overview': 'apps/index.md'
    - 'TensorFlow': 'apps/tensorflow.md'
    - 'TensorFlow Keras': 'apps/tensorflow-keras.md'
    - 'PyTorch': 'apps/pytorch.md'
    - 'MXNet': 'apps/mxnet.md'
    - 'Chainer': 'apps/chainer.md'
    - 'Others': 'apps/others.md'
  - 'Tips':
    - 'NVIDIA NGC': 'tips/ngc.md'
    - 'Remote Desktop': 'tips/remote-desktop.md'
    - 'AWS CLI': 'tips/awscli.md'
    - 'PuTTY': 'tips/putty.md'
    - 'Jupyter Notebook': 'tips/jupyter-notebook.md'
    - 'Singularity Global Client': 'tips/sregistry-cli.md'
    - 'Spack': 'tips/spack.md'
    - 'Datasets': 'tips/datasets.md'
    - 'Amazon ECR': 'tips/dl-amazon-ecr.md'
  - 'ABCI Cloud Storage':
    - 'Overview': 'abci-cloudstorage.md'
    - 'Accounts and Access keys': 'abci-cloudstorage/cs-account.md'
    - 'Usage': 'abci-cloudstorage/usage.md'
    - 'Data encryption': 'abci-cloudstorage/encryption.md'
    - 'Access Control (1) ': 'abci-cloudstorage/acl.md'
    - 'Access Control (2) ': 'abci-cloudstorage/policy.md'
    - 'Publishing Datasets': 'abci-cloudstorage/publishing-datasets.md'
    - 'Caution': 'abci-cloudstorage/caution.md'
  - 'ABCI Datasets': 'abci-datasets.md'
  - 'ABCI Singularity Endpoint': 'abci-singularity-endpoint.md'
  - 'FAQ': 'faq.md'
  - 'Known Issues': 'known-issues.md'
  - 'System Updates': 'system-updates.md'
  - 'Operation Status': 'https://abci.ai/en/about_abci/info.html'
  - 'Contact': 'contact.md'
  - 'Links':
    - 'ABCI Web page': 'https://abci.ai/'
    - 'ABCI User Portal Guide': 'https://docs.abci.ai/portal/en/'
    - 'ABCI User Portal (Registration)': 'https://portal.abci.ai/user/project_register_app.php?lang=en'
    - 'ABCI User Portal (Login)':  'https://portal.abci.ai/user/login.php?lang=en'
  - 'Japanese version': 'https://docs.abci.ai/ja/'
theme:
  name: 'material'
  favicon: 'img/favicon.png'
  logo: 'img/logo.png'
  language: 'en'
  palette:
    primary: 'red'
    accent: 'red'
  feature:
    tabs: false
markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - footnotes
