site_name: ABCI Portal Guide
site_description: ABCI Portal Guide
site_author: AIST
site_url: https://docs.abci.ai/portal/
copyright: 'Copyright &copy; 2024 National Institute of Advanced Industrial Science and Technology (AIST) / AIST Solutions Co. (AISol)'
nav: []
theme:
  name: 'material'
  palette:
    primary: 'blue'
  custom_dir: overrides
plugins:
  - redirects:
      redirect_maps:
        'index.md': 'https://docs.abci.ai/v3/portal/ja/'
