site_name: ABCI Portal Guide
site_description: ABCI Portal Guide, English version
site_author: AIST
site_url: https://docs.abci.ai/portal/en/
repo_url: https://github.com/aistairc/abci-docs
edit_uri: edit/master/portal/en/docs/
copyright: 'Copyright &copy; 2021 National Institute of Advanced Industrial Science and Technology (AIST)'
google_analytics:
  - 'UA-118371652-2'
  - 'auto'
nav:
  - 'Introduction': 'index.md'
  - '1. New Application': '01.md'
  - '2. User Portal': '02.md'
  - '3. User Management Authority': '03.md'
  - 'Links':
    - 'ABCI Web page': 'https://abci.ai/'
    - 'ABCI User Guide': 'https://docs.abci.ai/en/'
    - 'ABCI User Portal (Registration)': 'https://portal.abci.ai/user/project_register_app.php?lang=en'
    - 'ABCI User Portal (Login)':  'https://portal.abci.ai/user/login.php?lang=en'
theme:
  name: 'material'
  favicon: 'img/favicon.png'
  logo: 'img/logo.png'
  language: 'en'
  palette:
    primary: 'blue'
  features:
    - toc.integrate
extra:
  alternate:
    - name: 'English'
      link: 'https://docs.abci.ai/portal/en/'
    - name: '日本語'
      link: 'https://docs.abci.ai/portal/ja/'
markdown_extensions:
  - admonition
  - codehilite
  - attr_list
plugins:
  - search:
      lang: ja
