site_name: ABCI Portal Guide
site_description: ABCI Portal Guide, English version
site_author: AIST
site_url: https://docs.abci.ai/portal/en/
repo_url: https://github.com/aistairc/abci-docs
edit_uri: edit/master/portal/en/docs/
copyright: 'Copyright &copy; 2024 National Institute of Advanced Industrial Science and Technology (AIST) / AIST Solutions Co. (AISol)'
nav:
  - 'Introduction': 'index.md'
  - 'Links':
    - 'ABCI Web page': 'https://abci.ai/'
    - 'ABCI User Guide': 'https://docs.abci.ai/v3/en/'
theme:
  name: 'material'
  favicon: 'img/favicon.png'
  logo: 'img/logo.png'
  language: 'en'
  palette:
    primary: 'blue'
  features:
    - toc.integrate
  custom_dir: overrides
extra:
  alternate:
    - name: 'English'
      link: 'https://docs.abci.ai/v3/portal/en/'
    - name: '日本語'
      link: 'https://docs.abci.ai/v3/portal/ja/'
markdown_extensions:
  - admonition
  - codehilite
  - attr_list
plugins:
  - search:
      lang: ja
