site_name: ABCI User Guide
site_description: ABCI User Guide
site_author: AIST
site_url: https://docs.abci.ai/v3
copyright: 'Copyright &copy; 2024 National Institute of Advanced Industrial Science and Technology (AIST) / AIST Solutions Co. (AISol)'
nav:
  - 'ABCI User Guide 日本語版': 'https://docs.abci.ai/v3/ja/'
  - 'ABCI User Guide English version': 'https://docs.abci.ai/v3/en/'
theme:
  name: 'material'
  favicon: 'img/favicon.png'
  logo: 'img/logo.png'
  palette:
    primary: 'red'
markdown_extensions:
  - admonition
plugins:
  - redirects:
      redirect_maps:
        'index.md': 'https://docs.abci.ai/v3/ja/'
