site_name: ABCI Portal Guide
site_description: ABCI Portal Guide
site_author: AIST
site_url: https://docs.abci.ai/portal/
copyright: 'Copyright &copy; 2018 National Institute of Advanced Industrial Science and Technology (AIST)'
nav: []
theme:
  name: 'material'
  palette:
    primary: 'blue'
plugins:
  - redirects:
      redirect_maps:
        'index.md': 'https://docs.abci.ai/portal/ja/'
