site_name: ABCI User Guide & Portal Guide
site_description: ABCI User Guide & Portal Guide
site_author: AIST
site_url: https://docs.abci.ai/
copyright: 'Copyright &copy; 2018 National Institute of Advanced Industrial Science and Technology (AIST)'
nav:
  - 'ABCI User Guide 日本語版': 'https://docs.abci.ai/ja/'
  - 'ABCI User Guide English version': 'https://docs.abci.ai/en/'
  - 'ABCI Portal Guide 日本語版': 'https://docs.abci.ai/portal/ja/'
  - 'ABCI Portal Guide English version': 'https://docs.abci.ai/portal/ja/'
theme:
  name: 'material'
  favicon: 'img/favicon.png'
  logo: 'img/logo.png'
  palette:
    primary: 'red'
markdown_extensions:
  - admonition
plugins:
  - redirects:
      redirect_maps:
        'index.md': 'https://docs.abci.ai/ja/'
