site_name: ABCI 3.0 User Guide
site_description: ABCI 3.0 User Guide, English version
site_author: AIST
site_url: https://docs.abci.ai/v3/en
copyright: 'Copyright &copy; 2024 National Institute of Advanced Industrial Science and Technology (AIST) / AIST Solutions Co. (AISol)'
nav:
  - 'Introduction': 'index.md'
  - 'ABCI System Overview': 'system-overview.md'
  - 'Getting Started ABCI': 'getting-started.md'
  - 'Job Execution': 'job-execution.md'
  - 'Environment Modules': 'environment-modules.md'
  - 'Python': 'python.md'
  - 'MPI': 'mpi.md'
  - 'Containers': 'containers.md'
  - 'Development Tools': 'development-tools.md'
  - 'Tips':
    - 'GPUDirect Storage': 'tips/gds.md'
#  - 'ABCI Object Storage (Under Update)':
#    - 'Overview (Under Update)': 'abci-objectstorage/index.md'
#    - 'Accounts and Access keys (Under Update)': 'abci-objectstorage/account.md'
#    - 'Usage (Under Update)': 'abci-objectstorage/usage.md'
  - 'Open OnDemand':
    - 'Using Open OnDemand': 'open-ondemand/index.md'
  - 'System Updates': 'system-updates.md'
  - 'Contact': 'contact.md'
  - 'Various Requests':
    - 'Request for Communication with External Networks': 'requests/external-networks.md'
    - 'Request Related to Storage': 'requests/group-area-quota-increase.md'
extra:
  alternate:
    - name: 'English'
      link: 'https://docs.abci.ai/v3/en/'
    - name: '日本語'
      link: 'https://docs.abci.ai/v3/ja/'
theme:
  name: 'material'
  favicon: 'img/favicon.png'
  logo: 'img/logo.png'
  palette:
    primary: 'red'
  features:
    - toc.integrate
  custom_dir: overrides
markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - footnotes
plugins:
  - search:
      lang: en
